yum module

diff --git a/modules/public/elasticsearch/files/etc/init.d/elasticsearch.Debian.erb b/modules/public/elasticsearch/files/etc/init.d/elasticsearch.Debian.erb
--- a/modules/public/elasticsearch/files/etc/init.d/elasticsearch.Debian.erb
+++ b/modules/public/elasticsearch/files/etc/init.d/elasticsearch.Debian.erb
@@ -18,15 +18,15 @@ DESC="Elasticsearch Server <%= @resource[:instance] %>"
 DEFAULT=/etc/default/$NAME
 
 if [ `id -u` -ne 0 ]; then
-    echo "You need root privileges to run this script"
-    exit 1
+	echo "You need root privileges to run this script"
+	exit 1
 fi
 
 
 . /lib/lsb/init-functions
 
 if [ -r /etc/default/rcS ]; then
-    . /etc/default/rcS
+	. /etc/default/rcS
 fi
 
 
@@ -79,7 +79,7 @@ MAX_MAP_COUNT=262144
 
 # overwrite settings from default file
 if [ -f "$DEFAULT" ]; then
-    . "$DEFAULT"
+	. "$DEFAULT"
 fi
 
 # Define other required variables
@@ -91,115 +91,117 @@ export ES_HEAP_SIZE
 export ES_HEAP_NEWSIZE
 export ES_DIRECT_SIZE
 export ES_JAVA_OPTS
+export ES_JVM_OPTIONS
 export ES_CLASSPATH
 export ES_INCLUDE
+export ES_PATH_CONF
 export ES_GC_LOG_FILE
 
 if [ ! -x "$DAEMON" ]; then
-    echo "The elasticsearch startup script does not exists or it is not executable, tried: $DAEMON"
-    exit 1
+	echo "The elasticsearch startup script does not exists or it is not executable, tried: $DAEMON"
+	exit 1
 fi
 
 checkJava() {
-    if [ -x "$JAVA_HOME/bin/java" ]; then
-        JAVA="$JAVA_HOME/bin/java"
-    else
-        JAVA=`which java`
-    fi
+	if [ -x "$JAVA_HOME/bin/java" ]; then
+		JAVA="$JAVA_HOME/bin/java"
+	else
+		JAVA=`which java`
+	fi
 
-    if [ ! -x "$JAVA" ]; then
-        echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
-        exit 1
-    fi
+	if [ ! -x "$JAVA" ]; then
+		echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
+		exit 1
+	fi
 }
 
 case "$1" in
   start)
-    checkJava
+	checkJava
 
-    log_daemon_msg "Starting $DESC"
+	log_daemon_msg "Starting $DESC"
 
-    pid=`pidofproc -p $PID_FILE elasticsearch`
-    if [ -n "$pid" ] ; then
-        log_begin_msg "Already running."
-        log_end_msg 0
-        exit 0
-    fi
+	pid=`pidofproc -p $PID_FILE elasticsearch`
+	if [ -n "$pid" ] ; then
+		log_begin_msg "Already running."
+		log_end_msg 0
+		exit 0
+	fi
 
-    # Prepare environment
-    for DIR in "$DATA_DIR" "$LOG_DIR" "$WORK_DIR"; do
-        [ ! -z "$DIR" ] && mkdir -p "$DIR" && chown "$ES_USER":"$ES_GROUP" "$DIR"
-    done
-    if [ -n "$PID_FILE" ] && [ ! -e "$PID_FILE" ]; then
-        touch "$PID_FILE" && chown "$ES_USER":"$ES_GROUP" "$PID_FILE"
-    fi
+	# Prepare environment
+	for DIR in "$DATA_DIR" "$LOG_DIR" "$WORK_DIR"; do
+		[ ! -z "$DIR" ] && mkdir -p "$DIR" && chown "$ES_USER":"$ES_GROUP" "$DIR"
+	done
+	if [ -n "$PID_FILE" ] && [ ! -e "$PID_FILE" ]; then
+		touch "$PID_FILE" && chown "$ES_USER":"$ES_GROUP" "$PID_FILE"
+	fi
 
-    if [ -n "$MAX_OPEN_FILES" ]; then
-        ulimit -n $MAX_OPEN_FILES
-    fi
+	if [ -n "$MAX_OPEN_FILES" ]; then
+		ulimit -n $MAX_OPEN_FILES
+	fi
 
-    if [ -n "$MAX_LOCKED_MEMORY" ]; then
-        ulimit -l $MAX_LOCKED_MEMORY
-    fi
+	if [ -n "$MAX_LOCKED_MEMORY" ]; then
+		ulimit -l $MAX_LOCKED_MEMORY
+	fi
 
-    if [ -n "$MAX_MAP_COUNT" -a -f /proc/sys/vm/max_map_count ]; then
-        sysctl -q -w vm.max_map_count=$MAX_MAP_COUNT
-    fi
+	if [ -n "$MAX_MAP_COUNT" -a -f /proc/sys/vm/max_map_count ]; then
+		sysctl -q -w vm.max_map_count=$MAX_MAP_COUNT
+	fi
 
-    # Start Daemon
-    start-stop-daemon -d $ES_HOME --start --user "$ES_USER" -c "$ES_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
-    return=$?
-    if [ $return -eq 0 ]; then
-        i=0
-        timeout=10
-        # Wait for the process to be properly started before exiting
-        until { kill -0 `cat "$PID_FILE"`; } >/dev/null 2>&1
-        do
-            sleep 1
-            i=$(($i + 1))
-            if [ $i -gt $timeout ]; then
-                log_end_msg 1
-                exit 1
-            fi
-        done
-    fi
-    log_end_msg $return
-    exit $return
-    ;;
+	# Start Daemon
+	start-stop-daemon -d $ES_HOME --start --user "$ES_USER" -c "$ES_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
+	return=$?
+	if [ $return -eq 0 ]; then
+		i=0
+		timeout=10
+		# Wait for the process to be properly started before exiting
+		until { kill -0 `cat "$PID_FILE"`; } >/dev/null 2>&1
+		do
+			sleep 1
+			i=$(($i + 1))
+			if [ $i -gt $timeout ]; then
+				log_end_msg 1
+				exit 1
+			fi
+		done
+	fi
+	log_end_msg $return
+	exit $return
+	;;
   stop)
-    log_daemon_msg "Stopping $DESC"
+	log_daemon_msg "Stopping $DESC"
 
-    if [ -f "$PID_FILE" ]; then
-        start-stop-daemon --stop --pidfile "$PID_FILE" \
-            --user "$ES_USER" \
-            --quiet \
-            --retry forever/TERM/20 > /dev/null
-        if [ $? -eq 1 ]; then
-            log_progress_msg "$DESC is not running but pid file exists, cleaning up"
-        elif [ $? -eq 3 ]; then
-            PID="`cat $PID_FILE`"
-            log_failure_msg "Failed to stop $DESC (pid $PID)"
-            exit 1
-        fi
-        rm -f "$PID_FILE"
-    else
-        log_progress_msg "(not running)"
-    fi
-    log_end_msg 0
-    ;;
+	if [ -f "$PID_FILE" ]; then
+		start-stop-daemon --stop --pidfile "$PID_FILE" \
+			--user "$ES_USER" \
+			--quiet \
+			--retry forever/TERM/20 > /dev/null
+		if [ $? -eq 1 ]; then
+			log_progress_msg "$DESC is not running but pid file exists, cleaning up"
+		elif [ $? -eq 3 ]; then
+			PID="`cat $PID_FILE`"
+			log_failure_msg "Failed to stop $DESC (pid $PID)"
+			exit 1
+		fi
+		rm -f "$PID_FILE"
+	else
+		log_progress_msg "(not running)"
+	fi
+	log_end_msg 0
+	;;
   status)
-    status_of_proc -p $PID_FILE elasticsearch elasticsearch && exit 0 || exit $?
-    ;;
+	status_of_proc -p $PID_FILE elasticsearch elasticsearch && exit 0 || exit $?
+	;;
   restart|force-reload)
-    if [ -f "$PID_FILE" ]; then
-        $0 stop
-    fi
-    $0 start
-    ;;
+	if [ -f "$PID_FILE" ]; then
+		$0 stop
+	fi
+	$0 start
+	;;
   *)
-    log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
-    exit 1
-    ;;
+	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
+	exit 1
+	;;
 esac
 
 exit 0
